### ISSUE TITLE
Issue with syslog_outputs

### ISSUE THREAD

**Issue by Rx7TyreBurna** [dj-wasabi/ansible-ossec-server#9]
In this section (tasks/main.yml):

```
- name: Enable client-syslog if not running and ossec_server_config.syslog_outputs is given
  command: /var/ossec/bin/ossec-control enable client-syslog
  when: csyslog_running.stdout == '0' and ossec_server_config.syslog_outputs is defined

- name: Start client-syslog if not running and ossec_server_config.syslog_outputs is given
  command: /var/ossec/bin/ossec-control start client-syslog
  when: csyslog_running.stdout == '0' and ossec_server_config.syslog_outputs is defined

- name: Set ossec deploy facts for Debian
  set_fact:
    ossec_server_config_filename: ossec.conf
    ossec_init_name: ossec
  when: ansible_os_family == "Debian"

- name: Configure the ossec-server
  template: src=var-ossec-etc-ossec-server.conf.j2
            dest=/var/ossec/etc/{{ ossec_server_config_filename }}
            owner=root
            group=root
            mode=0644
  notify: restart ossec-server
  tags:
    - init
    - config
```

When using syslogs_outputs, I'd get an error with trying to start client syslog before the configurations were installed.
I resolved by moving the calls to ossec-control to after installation of the configuration file.

```
- name: Set ossec deploy facts for Debian
  set_fact:
    ossec_server_config_filename: ossec.conf
    ossec_init_name: ossec
  when: ansible_os_family == "Debian"

- name: Configure the ossec-server
  template: src=var-ossec-etc-ossec-server.conf.j2
            dest=/var/ossec/etc/{{ ossec_server_config_filename }}
            owner=root
            group=root
            mode=0644
  notify: restart ossec-server
  tags:
    - init
    - config

- name: Enable client-syslog if not running and ossec_server_config.syslog_outputs is given
  command: /var/ossec/bin/ossec-control enable client-syslog
  when: csyslog_running.stdout == '0' and ossec_server_config.syslog_outputs is defined

- name: Start client-syslog if not running and ossec_server_config.syslog_outputs is given
  command: /var/ossec/bin/ossec-control start client-syslog
  when: csyslog_running.stdout == '0' and ossec_server_config.syslog_outputs is defined

```
